<aside class="mst__svg">
  <h3>SVG</h3>

  <svg class="svg--landscape">
    <!-- JS will generate the code here -->
  </svg>

  <svg class="svg--portrait">
    <!-- JS will generate the code here -->
  </svg>

  <svg class="svg--mobile">
    <!-- JS will generate the code here -->
  </svg>

  <!-- if put in head the svg object will be null -->
  <script src="{{ site.url }}{{ site.scripts }}snap.svg-min.js"></script>
</aside>
